// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElBadge: typeof import('element-plus/es')['ElBadge']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
}
export {}
